[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "BMM-profile-collection-CAPS"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]

libc = "2.17"

[tasks]

[dependencies]

[feature.profile.dependencies]
ophyd = "*"
pyepics = "*"
ipython = "*"
tiled-client = ">=0.1.0b11,<0.2"
matplotlib = ">=3.9.3,<4"

[feature.profile.pypi-dependencies]
bluesky = ">=1.13"


[feature.tiled-server.dependencies]
tiled-server = ">=0.1.0b11,<0.2"
tiled-client = ">=0.1.0b11,<0.2"


[feature.tiled-server.pypi-dependencies]
canonicaljson = "*"



[environments]
profile = ["profile"]
local-tiled = ["tiled-server"]

