[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "BMM-profile-collection-CAPS"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]

libc = "2.17"



[dependencies]

[feature.profile.dependencies]
ophyd = "*"
pyepics = "*"
ipython = "*"
tiled-client = ">=0.1.0b11,<0.2"
matplotlib = ">=3.9.3,<4"
zict = "<3"
numpy = "<2"
bluesky = ">=1.13.0,<2"
python = "<3.11.9"

[feature.profile.tasks]
bsui = "ipython --profile-dir=profile_collection-caps"


[feature.tiled-server.dependencies]
tiled-server = ">=0.1.0b11,<0.2"
tiled-client = ">=0.1.0b11,<0.2"


[feature.tiled-server.pypi-dependencies]
canonicaljson = "*"

[feature.tiled-server.tasks]
init-local-tiled = "mkdir -p tiled_storage && tiled catalog init sqlite+aiosqlite:////$PWD/tiled_storage/catalog.db"
start_server = "tiled serve catalog /home/tcaswell/source/bnl/nsls2/BMM-profile_collection-CAPS/tiled_storage/catalog.db -w /home/tcaswell/source/bnl/nsls2/BMM-profile_collection-CAPS/tiled_storage/data/  --api-key=$TILED_API_KEY"

[feature.gateway.dependencies]
numpy = "*"
netifaces = "*"
dpkt = "*"

[feature.gateway.pypi-dependencies]
caproto = { git = "https://github.com/tacaswell/caproto.git", rev = "e91046e" }

[feature.gateway.tasks]
gateway = { cmd = "python complete_mirror.py --host $MIRROR_HOST --port 5064 --pvlist source.txt", cwd = "gateway" }




[environments]
profile = ["profile"]
local-tiled = ["tiled-server"]
gateway = ["gateway"]
