[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "BMM-profile-collection-CAPS"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

[feature.profile.dependencies]
ophyd = "*"
bluesky = "*"
pyepics = "*"
ipython = "*"

[feature.tiled-server.pypi-dependencies]
# tiled = { version = ">=0.1.0b12", extras = ["server"] }

[feature.tiled-server.dependencies]
numpy = ">=2.2.0,<3"
fastapi = ">=0.115.6,<0.116"
dask = ">=2024.12.0,<2025"
tifffile = ">=2024.9.20,<2025"
imagecodecs = ">=2024.9.22,<2025"
python = "<3.13"
tiled-server = ">=0.1.0a66,<0.2"
tiled-client = ">=0.1.0a66,<0.2"


[environments]
profile = ["profile"]
local-tiled = ["tiled-server"]

